name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "11eb1635f22142f684dced34e82ceebe" },
  { binding = "SHARE", id = "7c716082b87d418fb3c6792b2cb0c4ec" }
]
